name: Bug Report Form
description: File a bug report using interactive form
title: "[Bug]: "
labels: bug
assignees: TeRiRi114514
body:
  - type: textarea
    attributes:
      label: What happened?
      description: A clear and concise description of what the bug is.
      placeholder: Tell us what you see!
    validations:
      required: true
  - type: textarea
    attributes:
      label: Steps to reproduce
      description: How can we reproduce the issue?
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
  - type: input
    attributes:
      label: Operating system
      placeholder: e.g. Windows 11, macOS Ventura
  - type: input
    attributes:
      label: Browser
      placeholder: e.g. Chrome 120, Safari 17
